DROP DATABASE IF EXISTS `tragaldaba`;

CREATE DATABASE tragaldaba DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,CREATE TEMPORARY TABLES,DROP,INDEX,ALTER ON tragaldaba.* TO tragaldaba@localhost IDENTIFIED BY 'tragaldaba';